

export const testimonialsConfig = {
  heading: { en: 'Early believers.', ne: 'अगाडि अपनाउने विश्वासिला।' },
  sub: { en: 'What early access members and investors are saying.', ne: 'अगाडि पहुँच सदस्य र लगानीकर्ताहरू के भन्छन्।' },
  items: [
    { quote: { en: "As a brand, the targeting precision and community depth on Tirbeo is exactly what marketing needs today. We're all in.", ne: 'एउटा ब्रान्डको रूपमा, तिर्बिओको लक्ष्य निशाना र समुदाय गहिराइ बजार प्रचारको लागि आज आवश्यक पर्ने कुरा हो। हामी पूर्ण रूपमा सामिल छौं।' }, name: 'Claire Beaulieu', role: 'CMO', avatar: 'https://randomuser.me/api/portraits/women/44.jpg' },
    { quote: { en: "We found Tirbeo months before launch and the early community already feels more real than anything on legacy social.", ne: 'हामीले तिर्बिओ सुरुवातभन्दा महिनौं अगाडि पायौं र अगाडिको समुदाय पुरानो सामाजिक भन्दा बढी वास्तविक लाग्छ।' }, name: 'Daniel Roth', role: 'Partner', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
    { quote: { en: "The threaded discussions blow Discord away. No noise, just real conversations with a beginning, middle, and end.", ne: 'थ्रेडेड छलफलले डिस्कोर्डलाई उछिन्छ। कुनै हल्ला छैन, सुरु, मध्य र अन्त भएको वास्तविक कुराकानी मात्र।' }, name: 'Maya Lindqvist', role: 'Designer', avatar: 'https://randomuser.me/api/portraits/women/68.jpg' },
    { quote: { en: "Shared libraries I actually own — I saved three posts and carried them straight into another community. That's the future.", ne: 'मेरै स्वामित्वका साझा लाइब्रेरीहरू — मैले तीन पोस्ट बचाएँ र अर्को समुदायमा लगें। त्यही भविष्य हो।' }, name: 'Aarav Sharma', role: 'Creator', avatar: 'https://randomuser.me/api/portraits/men/76.jpg' },
    { quote: { en: "Live sessions capped for real connection, not crowds. We booked Friday and it felt like a room, not a stadium.", ne: 'वास्तविक जडानको लागि सीमित लाइभ सेसन, भीडको लागि होइन। शुक्रवार बुक गर्यौं र त्यो रंगशाला हैन, कोठा जस्तो लाग्यो।' }, name: 'Priya Nair', role: 'Community Lead', avatar: 'https://randomuser.me/api/portraits/women/12.jpg' },
    { quote: { en: "Privacy by default changed how our team talks. Every message sealed, only who we chose can read it.", ne: 'पूर्वनिर्धारित गोपनीयताले हाम्रो टोलीको कुराकानी परिवर्तन गर्यो। हरेक सन्देश सिल, हामीले छानेकाले मात्र पढ्न सक्छन्।' }, name: "Liam O'Connor", role: 'Founder', avatar: 'https://randomuser.me/api/portraits/men/45.jpg' },
    { quote: { en: "Finally a platform that respects my attention. No algorithm sorting my friends. Just the people I want to hear from.", ne: 'अन्तमा एउटा प्ल्याटफर्म जसले मेरो ध्यानको सम्मान गर्छ। कुनै एल्गोरिदमले मेरा साथीलाई छान्दैन।' }, name: 'Sofia Marchetti', role: 'Writer', avatar: 'https://randomuser.me/api/portraits/women/90.jpg' },
    { quote: { en: "We moved our whole studio into Tirbeo Collab. The focused interface keeps the work front and center, not the noise.", ne: 'हामीले सबै स्टुडियो तिर्बिओ कोलाबमा ल्यायौं। केन्द्रित इन्टरफेसले कामलाई केन्द्रमा राख्छ।' }, name: 'Noah Bergström', role: 'Director', avatar: 'https://randomuser.me/api/portraits/men/85.jpg' },
    { quote: { en: "I left three other apps in a week. Tirbeo is the only feed where I actually know everyone I'm talking to.", ne: 'मैले एक हप्तामा अरू तीन एप छोडें। तिर्बिओ मात्र त्यो फिड हो जहाँ म सबैसँग चिन्छु।' }, name: 'Hana Kim', role: 'Product Designer', avatar: 'https://randomuser.me/api/portraits/women/25.jpg' },
    { quote: { en: "The live rooms feel intimate even at 40 people. Conversations breathe instead of getting buried in a feed.", ne: 'लाइभ रूम ४० जनामा पनि नजिक लाग्छ। कुराकानी फिडमा हराइन बरु सास फेर्छ।' }, name: 'Marcus Webb', role: 'Indie Hacker', avatar: 'https://randomuser.me/api/portraits/men/52.jpg' },
    { quote: { en: "Saved a whole research thread to my library and reused it in two communities. That portability is unreal.", ne: 'मैले एउटा अनुसन्धान थ्रेड लाइब्रेरीमा बचाएँ र दुई समुदायमा फेरि प्रयोग गरें। त्यो पोर्टेबिलिटी अविश्वसनीय छ।' }, name: 'Yuki Tanaka', role: 'Researcher', avatar: 'https://randomuser.me/api/portraits/women/33.jpg' },
  ],
};